import type { Workout, WeeklyWorkoutSummary } from "@runcoach/types";

export const workouts: Workout[] = [
  {
    id: "w-1",
    date: "2026-08-25",
    title: "Easy recovery run",
    type: "easy",
    durationMinutes: 38,
    distanceKm: 6.4,
    averageHeartRate: 148,
    effort: "easy",
    notes: "Relaxed aerobic run with light strides at the end.",
    source: "strava",
    completed: true,
    tags: ["aerobic", "recovery"],
  },
  {
    id: "w-2",
    date: "2026-08-27",
    title: "Tempo session",
    type: "tempo",
    durationMinutes: 51,
    distanceKm: 8.7,
    averageHeartRate: 162,
    effort: "hard",
    notes: "3 x 10 minutes at tempo effort with 2 minute jog recoveries.",
    source: "strava",
    completed: true,
    tags: ["tempo", "threshold"],
  },
  {
    id: "w-3",
    date: "2026-08-29",
    title: "Long run",
    type: "long",
    durationMinutes: 97,
    distanceKm: 18.1,
    averageHeartRate: 156,
    effort: "moderate",
    notes: "Steady long run with last 20 minutes slightly faster.",
    source: "strava",
    completed: true,
    tags: ["long-run", "aerobic"],
  },
  {
    id: "w-4",
    date: "2026-09-01",
    title: "Vo2 max intervals",
    type: "interval",
    durationMinutes: 46,
    distanceKm: 7.9,
    averageHeartRate: 176,
    effort: "hard",
    notes: "6 x 800m at 5k rhythm with 2 minute recovery.",
    source: "manual",
    completed: true,
    tags: ["intervals", "vo2"],
  },
  {
    id: "w-5",
    date: "2026-09-03",
    title: "Easy run",
    type: "easy",
    durationMinutes: 34,
    distanceKm: 5.8,
    averageHeartRate: 147,
    effort: "easy",
    notes: "Easy aerobic run to absorb the previous hard session.",
    source: "manual",
    completed: true,
    tags: ["recovery"],
  },
  {
    id: "w-6",
    date: "2026-09-05",
    title: "Progression run",
    type: "tempo",
    durationMinutes: 59,
    distanceKm: 10.3,
    averageHeartRate: 165,
    effort: "moderate",
    notes: "Started easy and finished strong over the final 15 minutes.",
    source: "strava",
    completed: true,
    tags: ["progression"],
  },
  {
    id: "w-7",
    date: "2026-09-08",
    title: "Recovery run",
    type: "recovery",
    durationMinutes: 29,
    distanceKm: 4.9,
    averageHeartRate: 142,
    effort: "easy",
    notes: "Short, low-intensity run after the weekend long effort.",
    source: "manual",
    completed: true,
    tags: ["recovery"],
  },
  {
    id: "w-8",
    date: "2026-08-18",
    title: "Easy aerobic run",
    type: "easy",
    durationMinutes: 42,
    distanceKm: 7.1,
    averageHeartRate: 149,
    effort: "easy",
    notes: "Relaxed aerobic work on a flat route.",
    source: "strava",
    completed: true,
    tags: ["aerobic"],
  },
  {
    id: "w-9",
    date: "2026-08-20",
    title: "Threshold repeats",
    type: "tempo",
    durationMinutes: 55,
    distanceKm: 9.2,
    averageHeartRate: 164,
    effort: "hard",
    notes: "Four controlled threshold repeats with short jog recoveries.",
    source: "strava",
    completed: true,
    tags: ["tempo", "threshold"],
  },
  {
    id: "w-10",
    date: "2026-08-22",
    title: "Steady long run",
    type: "long",
    durationMinutes: 88,
    distanceKm: 16.5,
    averageHeartRate: 154,
    effort: "moderate",
    notes: "Steady endurance run with an even effort throughout.",
    source: "strava",
    completed: true,
    tags: ["long-run"],
  },
  {
    id: "w-11",
    date: "2026-08-11",
    title: "Recovery jog",
    type: "recovery",
    durationMinutes: 31,
    distanceKm: 5.2,
    averageHeartRate: 141,
    effort: "easy",
    notes: "Kept deliberately light after the weekend long run.",
    source: "strava",
    completed: true,
    tags: ["recovery"],
  },
  {
    id: "w-12",
    date: "2026-08-13",
    title: "Hill intervals",
    type: "interval",
    durationMinutes: 48,
    distanceKm: 7.6,
    averageHeartRate: 171,
    effort: "hard",
    notes: "Short hill repetitions focused on strong running mechanics.",
    source: "manual",
    completed: true,
    tags: ["hills", "strength"],
  },
  {
    id: "w-13",
    date: "2026-08-15",
    title: "Long aerobic run",
    type: "long",
    durationMinutes: 102,
    distanceKm: 19.4,
    averageHeartRate: 153,
    effort: "moderate",
    notes: "Long aerobic session with a relaxed final section.",
    source: "strava",
    completed: true,
    tags: ["long-run", "aerobic"],
  },
  {
    id: "w-14",
    date: "2026-08-04",
    title: "Easy base run",
    type: "easy",
    durationMinutes: 39,
    distanceKm: 6.3,
    averageHeartRate: 146,
    effort: "easy",
    notes: "Comfortable base mileage on a warm morning.",
    source: "strava",
    completed: true,
    tags: ["aerobic"],
  },
  {
    id: "w-15",
    date: "2026-08-06",
    title: "Tempo progression",
    type: "tempo",
    durationMinutes: 52,
    distanceKm: 8.8,
    averageHeartRate: 161,
    effort: "moderate",
    notes: "Progressed smoothly from easy pace into tempo effort.",
    source: "strava",
    completed: true,
    tags: ["tempo", "progression"],
  },
  {
    id: "w-16",
    date: "2026-08-08",
    title: "Long run",
    type: "long",
    durationMinutes: 94,
    distanceKm: 17.8,
    averageHeartRate: 155,
    effort: "moderate",
    notes: "Consistent long run focused on building durability.",
    source: "strava",
    completed: true,
    tags: ["long-run"],
  },
  {
    id: "w-17",
    date: "2026-07-28",
    title: "Easy recovery run",
    type: "recovery",
    durationMinutes: 35,
    distanceKm: 5.8,
    averageHeartRate: 143,
    effort: "easy",
    notes: "Light recovery mileage with relaxed form.",
    source: "strava",
    completed: true,
    tags: ["recovery"],
  },
  {
    id: "w-18",
    date: "2026-07-30",
    title: "Speed session",
    type: "interval",
    durationMinutes: 44,
    distanceKm: 7.3,
    averageHeartRate: 174,
    effort: "hard",
    notes: "Short repetitions with full control and consistent form.",
    source: "manual",
    completed: true,
    tags: ["speed"],
  },
  {
    id: "w-19",
    date: "2026-08-01",
    title: "Weekend long run",
    type: "long",
    durationMinutes: 91,
    distanceKm: 17.1,
    averageHeartRate: 152,
    effort: "moderate",
    notes: "Steady weekend endurance session.",
    source: "strava",
    completed: true,
    tags: ["long-run"],
  },
];

export const weeklyWorkoutSummaries: WeeklyWorkoutSummary[] = [
  {
    weekStart: "2026-07-27",
    weekLabel: "Week 31",
    totalDistanceKm: 30.2,
    totalMinutes: 170,
    workouts: workouts.slice(16, 19),
  },
  {
    weekStart: "2026-08-03",
    weekLabel: "Week 32",
    totalDistanceKm: 32.9,
    totalMinutes: 185,
    workouts: workouts.slice(13, 16),
  },
  {
    weekStart: "2026-08-10",
    weekLabel: "Week 33",
    totalDistanceKm: 32.2,
    totalMinutes: 181,
    workouts: workouts.slice(10, 13),
  },
  {
    weekStart: "2026-08-17",
    weekLabel: "Week 34",
    totalDistanceKm: 32.8,
    totalMinutes: 185,
    workouts: workouts.slice(7, 10),
  },
  {
    weekStart: "2026-08-24",
    weekLabel: "Week 35",
    totalDistanceKm: 33.2,
    totalMinutes: 186,
    workouts: workouts.slice(0, 3),
  },
  {
    weekStart: "2026-08-31",
    weekLabel: "Week 36",
    totalDistanceKm: 28.0,
    totalMinutes: 129,
    workouts: workouts.slice(3, 6),
  },
  {
    weekStart: "2026-09-07",
    weekLabel: "Week 37",
    totalDistanceKm: 4.9,
    totalMinutes: 29,
    workouts: workouts.slice(6),
  },
];
